### ISSUE TITLE
token

### ISSUE THREAD

**Issue by Jacobneedshelppls** [Disc0rdTools/NitroSniper#4]
dont know what is a token or where to get a token

i know this isnt really your problem but i really need help here

**Comment by Disc0rdTools** [comment]
Hey!
A token is a unique ID which is used to login to Discord. You can find your token by looking at the http requests sent by your browser.
Here's a video I found on YouTube that explains it all: https://www.youtube.com/watch?v=1dva3YqBI2E
You can also buy discord tokens which are on many servers to snipe nitros faster, they are usually sold between $0.15 and $0.30.
