### ISSUE TITLE
is a token  grabber yall

### ISSUE THREAD

**Issue by DartTools** [Disc0rdTools/NitroSniper#5]

**Comment by Disc0rdTools** [comment]
Hey, 
Why lie?

**Comment by Disc0rdTools** [comment]
I'd like to see the proof you've got, because the sniper has over 900 downloads, and it's the first time I've seen an issue like that
Need I remind you that its code is open source?

**Comment by Disc0rdTools** [comment]
OK, I'm closing the issue because I still haven't had any answers from you.
Have a nice day.
